# Generated by Django 5.2.17 on 2026-09-08 12:47

import apps.resources.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('applies_to', models.CharField(choices=[('VENUE', 'Venues'), ('VEHICLE', 'Vehicles'), ('BOTH', 'Both')], default='VENUE', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_seeded', models.BooleanField(default=False, help_text='Created at installation rather than by an administrator.')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('resource_type', models.CharField(choices=[('VENUE', 'Venue'), ('VEHICLE', 'Vehicle')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under maintenance')], default='ACTIVE', max_length=15)),
                ('approval_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_class', models.CharField(default='CAR', max_length=20)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('year', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('transmission', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('road_tax_expiry', models.DateField()),
            ],
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resource')),
                ('venue_type', models.CharField(choices=[('MOOT_COURT', 'Moot court'), ('SEMINAR', 'Seminar room'), ('MEETING', 'Meeting room'), ('LECTURE', 'Lecture room'), ('DISCUSSION', 'Discussion room'), ('CONFERENCE', 'Conference room')], max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('opens_at', models.TimeField(default='08:00')),
                ('closes_at', models.TimeField(default='22:00')),
            ],
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='ResourceFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.facility')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='facilities',
            field=models.ManyToManyField(blank=True, through='resources.ResourceFacility', to='resources.facility'),
        ),
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.resources.models.resource_image_path)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='0 is the main image.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='resources.resource')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='resourcefacility',
            constraint=models.UniqueConstraint(fields=('resource', 'facility'), name='unique_resource_facility'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'status'], name='resources_r_resourc_e067d0_idx'),
        ),
    ]
