# Generated by Django 5.2.17 on 2026-09-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('name',)},
        ),
    ]
