# Generated by Django 5.2.17 on 2026-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_vehicle_options_alter_venue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_slug',
            field=models.SlugField(blank=True, help_text='Placeholder drawing used when no photograph has been uploaded.', max_length=40),
        ),
    ]
