# Generated by Django 5.2.17 on 2026-09-08 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('start_date',),
                'indexes': [models.Index(fields=['start_date'], name='bookings_ac_start_d_5db861_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_times', models.JSONField(default=dict)),
                ('starts_on', models.DateField()),
                ('repeat_until', models.DateField()),
                ('purpose', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.resource')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.academicterm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'booking series',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('purpose', models.TextField(help_text='Visible to the requester and on the record.')),
                ('attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('driver_arrangement', models.CharField(blank=True, choices=[('SELF', 'Self-drive'), ('VMU', 'Driver supplied by the Vehicle Management Unit')], max_length=5)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_contact', models.CharField(blank=True, max_length=20)),
                ('location_from', models.CharField(blank=True, max_length=150)),
                ('location_to', models.CharField(blank=True, max_length=150)),
                ('passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('management_approved', models.BooleanField(default=False)),
                ('management_approved_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_decided', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='resources.resource')),
                ('user', models.ForeignKey(help_text='The person the booking is for.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingseries')),
            ],
            options={
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='KeyHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by_name', models.CharField(blank=True, help_text='Who physically collected the key.', max_length=150)),
                ('collected_by_contact', models.CharField(blank=True, max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('returned_by_name', models.CharField(blank=True, max_length=150)),
                ('condition_notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='key_handover', to='bookings.booking')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keys_issued', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keys_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='bookings.academicterm')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'start_at'], name='bookings_bo_resourc_a1a698_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-start_at'], name='bookings_bo_user_id_c7bbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_at'], name='bookings_bo_status_1b0540_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_at'], name='bookings_bo_start_a_042c97_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['series'], name='bookings_bo_series__ce9d08_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='booking_ends_after_it_starts'),
        ),
    ]
