# Generated by Django 5.2.17 on 2026-09-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_overlap_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=150)),
                ('resource_code', models.CharField(max_length=30)),
                ('resource_name', models.CharField(max_length=120)),
                ('resource_type', models.CharField(max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('purpose', models.TextField(blank=True)),
                ('key_issued_at', models.DateTimeField(blank=True, null=True)),
                ('key_returned_at', models.DateTimeField(blank=True, null=True)),
                ('original_created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-start_at',),
                'indexes': [models.Index(fields=['start_at'], name='bookings_bo_start_a_a7327b_idx')],
            },
        ),
    ]
