# Generated by Django 5.2.17 on 2026-09-10 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_vehicle_decisions(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for booking in Booking.objects.filter(resource__resource_type="VEHICLE"):
        booking.driver_arrangement = "VMU"
        booking.management_status = "APPROVED" if booking.management_approved else "PENDING"
        booking.management_decided_at = booking.management_approved_at
        booking.save(
            update_fields=[
                "driver_arrangement",
                "management_status",
                "management_decided_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingarchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='management_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='management_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_management_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='management_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='management_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Awaiting management approval'), ('APPROVED', 'Management approved'), ('REJECTED', 'Management did not approve')], default='', max_length=10),
        ),
        migrations.RunPython(preserve_vehicle_decisions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='booking',
            name='management_approved',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='management_approved_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver_arrangement',
            field=models.CharField(blank=True, choices=[('VMU', 'Driver supplied by the Vehicle Management Unit')], max_length=5),
        ),
    ]
