# Generated by Django 5.2.17 on 2026-09-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_management_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.TextField(help_text='Tell us what the booking is for.'),
        ),
    ]
