# Generated by Django 5.2.17 on 2026-09-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Room and Vehicle Booking', max_length=80)),
                ('subtitle', models.CharField(default='Ahmad Ibrahim Kulliyyah of Laws · IIUM', max_length=120)),
                ('organisation', models.CharField(default='Ahmad Ibrahim Kulliyyah of Laws', max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('logo_alt', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_heading', models.CharField(default='Booking enquiries', max_length=60)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'site content',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
