# Generated by Django 5.2.17 on 2026-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_setting_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='iium_logo',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='IIUM logo'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='iium_logo_alt',
            field=models.CharField(default='International Islamic University Malaysia', max_length=200, verbose_name='IIUM logo description'),
        ),
    ]
