# Generated by Django 5.2.17 on 2026-09-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_iium_logo_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='copyright_notice',
            field=models.CharField(default='International Islamic University Malaysia. All rights reserved.', help_text='Shown after the copyright sign and the current year.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='email',
            field=models.TextField(blank=True, help_text='One address per line.', verbose_name='email addresses'),
        ),
    ]
