# Generated by Django 5.2.17 on 2026-09-08 12:47

import apps.accounts.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='The login field. IIUM addresses identify staff and students.', max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150)),
                ('identification_number', models.CharField(blank=True, help_text='Collected for documentation and reporting (decision 18). Not a login credential.', max_length=30, null=True, unique=True, verbose_name='matriculation or staff number')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{7,20}$', 'Enter a telephone number using digits, spaces, and + - ( ) only.')])),
                ('role', models.CharField(choices=[('USER', 'User'), ('APPROVER', 'Approver'), ('ADMINISTRATOR', 'Administrator')], default='USER', max_length=20)),
                ('affiliation', models.CharField(choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('STAFF', 'Staff'), ('PUBLIC', 'Member of the public')], default='STUDENT', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('licence_number', models.CharField(blank=True, max_length=30, verbose_name='driving licence number')),
                ('licence_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'), models.Index(fields=['affiliation'], name='accounts_us_affilia_6ea9d3_idx')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
