# Generated by Django 5.2.17 on 2026-09-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='licence_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='licence_number',
        ),
    ]
