# Generated by Django 5.2.17 on 2026-09-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_totp_device_recovery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, help_text='Used on booking records and reports. It is not your login.', max_length=30, null=True, unique=True, verbose_name='matriculation or staff number'),
        ),
    ]
