# Generated by Django 5.2.17 on 2026-09-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_identification_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='You sign in with this email.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, help_text='Your matriculation or staff number.', max_length=30, null=True, unique=True, verbose_name='matriculation or staff number'),
        ),
    ]
